# Generated by Django 4.2.6 on 2024-05-26 13:12

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Laoran',
            new_name='Laporan',
        ),
        migrations.AlterModelOptions(
            name='berita',
            options={'verbose_name_plural': 'Berita'},
        ),
        migrations.AlterModelOptions(
            name='kontak',
            options={'verbose_name_plural': 'Kontak'},
        ),
        migrations.AlterModelOptions(
            name='laporan',
            options={'verbose_name_plural': 'Laporan'},
        ),
        migrations.AlterModelOptions(
            name='profil',
            options={'verbose_name_plural': 'Profil'},
        ),
        migrations.AlterModelOptions(
            name='slide',
            options={'verbose_name_plural': 'Slide'},
        ),
        migrations.AlterModelOptions(
            name='statis',
            options={'verbose_name_plural': 'Statis'},
        ),
        migrations.AlterField(
            model_name='berita',
            name='gambar',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=80, scale=None, size=[575, 200], upload_to='gambar/banner'),
        ),
        migrations.AlterField(
            model_name='berita',
            name='keterangan_berita',
            field=models.CharField(blank=True, choices=[('Baru', 'Baru'), ('Lama', 'Lama')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='gambar',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=80, scale=None, size=[575, 200], upload_to='gambar/profil', verbose_name='Gambar (1920 x 1200 pixel)'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='gambar_slide',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=80, scale=None, size=[575, 200], upload_to='gambar/slide'),
        ),
    ]
