# Generated by Django 4.2.6 on 2024-05-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_laporan_options_rename_telpon_laporan_nilai_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laporan',
            options={'verbose_name_plural': 'Laporan'},
        ),
        migrations.RenameField(
            model_name='laporan',
            old_name='nilai',
            new_name='nilai_alquran',
        ),
        migrations.AddField(
            model_name='laporan',
            name='alamat',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='laporan',
            name='lembaga',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='laporan',
            name='nama_santri',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='laporan',
            name='nilai_fiqih',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='laporan',
            name='nilai_tauhid',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='laporan',
            name='ttl',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='laporan',
            name='wali_santri',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
