# Generated by Django 4.2.6 on 2024-06-10 17:28

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_laporan_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laporan',
            name='gambar',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=80, scale=None, size=[200, 200], upload_to='gambar/banner'),
        ),
        migrations.AlterField(
            model_name='laporan',
            name='alamat',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='laporan',
            name='lembaga',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='laporan',
            name='nama_santri',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='laporan',
            name='nilai_alquran',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='laporan',
            name='nilai_fiqih',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='laporan',
            name='nilai_tauhid',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='laporan',
            name='ttl',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='laporan',
            name='wali_santri',
            field=models.TextField(max_length=20, null=True),
        ),
    ]
