# Generated by Django 4.2.6 on 2024-06-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_laporan_gambar_alter_laporan_alamat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laporan',
            name='alamat',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='laporan',
            name='lembaga',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='laporan',
            name='nama_santri',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='laporan',
            name='nilai_alquran',
            field=models.IntegerField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='laporan',
            name='nilai_fiqih',
            field=models.IntegerField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='laporan',
            name='nilai_tauhid',
            field=models.IntegerField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='laporan',
            name='ttl',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='laporan',
            name='wali_santri',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
