# Generated by Django 4.2.6 on 2024-06-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_laporan_alamat_alter_laporan_lembaga_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laporan',
            name='nilai_alquran',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='laporan',
            name='nilai_fiqih',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='laporan',
            name='nilai_tauhid',
            field=models.IntegerField(null=True),
        ),
    ]
