# Generated by Django 4.2.6 on 2024-06-12 16:43

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_laporan_nilai_alquran_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Santri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_santri', models.CharField(max_length=50, null=True)),
                ('gambar', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=80, scale=None, size=[200, 200], upload_to='gambar/banner')),
                ('kamar', models.CharField(max_length=50, null=True)),
                ('wali_santri', models.CharField(max_length=50, null=True)),
                ('ttl', models.CharField(max_length=50, null=True)),
                ('alamat', models.CharField(max_length=100, null=True)),
                ('lembaga', models.CharField(max_length=50, null=True)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Santri',
            },
        ),
        migrations.RemoveField(
            model_name='laporan',
            name='alamat',
        ),
        migrations.RemoveField(
            model_name='laporan',
            name='gambar',
        ),
        migrations.RemoveField(
            model_name='laporan',
            name='lembaga',
        ),
        migrations.RemoveField(
            model_name='laporan',
            name='nama_santri',
        ),
        migrations.RemoveField(
            model_name='laporan',
            name='ttl',
        ),
        migrations.RemoveField(
            model_name='laporan',
            name='wali_santri',
        ),
    ]
