# Generated by Django 4.2.6 on 2024-06-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_santri_remove_laporan_alamat_remove_laporan_gambar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='santri',
            name='tanggal',
        ),
        migrations.AddField(
            model_name='laporan',
            name='tanggal_publish',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
