# Generated by Django 4.2.6 on 2024-06-13 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_laporan_nama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laporan',
            name='nama',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laporans', to='website.santri'),
        ),
        migrations.AlterField(
            model_name='laporan',
            name='tanggal_publish',
            field=models.DateTimeField(null=True),
        ),
    ]
