# Generated by Django 4.2.6 on 2024-06-16 16:13

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_laporan_pelanggaran_alter_laporan_kamar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='gambar',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=80, scale=None, size=[200, 200], upload_to='gambar/banner'),
        ),
        migrations.AlterField(
            model_name='berita',
            name='tanggal_upload',
            field=models.DateField(null=True),
        ),
    ]
