# Generated by Django 4.2.6 on 2024-06-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_alter_berita_gambar_alter_berita_tanggal_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='gambar',
            field=models.ImageField(null=True, upload_to='gambar/banner'),
        ),
    ]
