# Generated by Django 4.2.6 on 2024-06-16 17:46

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_alter_berita_gambar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='berita',
            name='slug',
        ),
        migrations.AlterField(
            model_name='berita',
            name='gambar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=80, scale=None, size=[400, 300], upload_to='gambar/banner'),
        ),
        migrations.AlterField(
            model_name='berita',
            name='keterangan',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
