# Generated by Django 4.2.6 on 2024-06-16 18:01

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_alter_berita_gambar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='gambar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=80, scale=None, size=[250, 200], upload_to='gambar/banner'),
        ),
        migrations.AlterField(
            model_name='berita',
            name='keterangan_berita',
            field=models.CharField(blank=True, choices=[('Baru', 'Baru'), ('Lama', 'Lama')], default='KETERANGAN.Baru', max_length=200, null=True),
        ),
    ]
