# Generated by Django 4.2.6 on 2024-06-16 18:06

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_alter_berita_gambar_alter_berita_keterangan_berita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='gambar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=80, scale=None, size=[300, 200], upload_to='gambar/banner'),
        ),
        migrations.AlterField(
            model_name='berita',
            name='keterangan_berita',
            field=models.CharField(choices=[('Baru', 'Baru'), ('Lama', 'Lama')], default='Baru', max_length=50),
        ),
    ]
