# Generated by Django 4.2.6 on 2024-06-16 18:47

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_alter_berita_gambar_alter_berita_keterangan_berita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='gambar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=80, scale=None, size=[800, 600], upload_to='gambar/banner'),
        ),
    ]
