# Generated by Django 4.2.6 on 2024-06-20 16:51

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_alter_berita_gambar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='keterangan',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='tanggal_upload',
        ),
        migrations.AddField(
            model_name='profil',
            name='jabatan',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='gambar',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=80, scale=None, size=[200, 200], upload_to='gambar/profil', verbose_name='Gambar (1920 x 1200 pixel)'),
        ),
    ]
