# Generated by Django 4.2.6 on 2024-06-20 19:03

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_remove_profil_keterangan_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kontak',
            old_name='subject',
            new_name='jabatan',
        ),
        migrations.RemoveField(
            model_name='kontak',
            name='isi',
        ),
        migrations.AddField(
            model_name='kontak',
            name='gambar',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=80, scale=None, size=[200, 200], upload_to='gambar/profil', verbose_name='Gambar (1920 x 1200 pixel)'),
        ),
        migrations.AddField(
            model_name='kontak',
            name='nama_fb',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='kontak',
            name='nama_ig',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
