# Generated by Django 4.2.6 on 2024-06-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_remove_kontak_email_remove_kontak_nama_fb_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='nama_fb',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='nama_ig',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='no_whatsapp',
        ),
        migrations.AddField(
            model_name='kontak',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='kontak',
            name='nama_fb',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='kontak',
            name='nama_ig',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='kontak',
            name='no_whatsapp',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
