# Generated by Django 4.2.6 on 2024-06-20 21:19

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_remove_profil_jabatan_remove_profil_nama_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='gambar_slide',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=80, scale=None, size=[800, 800], upload_to='gambar/slide'),
        ),
    ]
