# Generated by Django 4.2.6 on 2024-06-20 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_alter_slide_gambar_slide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='gambar_slide',
            field=models.ImageField(null=True, upload_to='gambar/slide'),
        ),
    ]
