# Generated by Django 4.2.6 on 2024-06-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_alter_slide_gambar_slide'),
    ]

    operations = [
        migrations.AddField(
            model_name='laporan',
            name='niup',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
