# Generated by Django 4.2.6 on 2024-07-26 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0034_laporan_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laporan',
            name='password',
        ),
    ]
